stages:
  - build
  - deploy

push-dev:
  stage: build
  image: docker:latest
  only:
    - develop
    - master
  services:
    - docker:dind
  before_script:
    - docker version
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  after_script:
    - docker logout $CI_REGISTRY

deploy-dev:
  stage: deploy
  image: kroniak/ssh-client
  only:
    - develop
    - master
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 600 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh $SSH_HOST "docker pull $CI_REGISTRY_IMAGE"
    - ssh $SSH_HOST "cd /home/$SSH_USER/happy; docker-compose down; docker-compose up -d"
