version: "3.3"

services:
  happy-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: happy-database
    networks:
      - happy-network
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  happy-backend:
    depends_on:
      - happy-database
    image: michi1893/happy-backend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - happy-network

networks: happy-network:
