openapi: "3.0.0"
info:
  description: "API for the Web-Engineering II project hAPPy"
  version: "0"
  title: "hAPPy"
servers:
  - url: "localhost"
tags:
  - name: "face"
  - name: "user"
  - name: "statistic"
  - name: "image"
paths:
  "/api/image":
    post:
      tags:
        - "image"
      description: "Uploads a single image file."
      operationId: "post-image"
      requestBody:
        description: "MultipartFormDataInput of file"
        content:
          multipart/form-data:
            schema:
              # EDIT REF
              $ref: "#/components/schemas/Emotion"
        required: false
      responses:
        200:
          description: "Uploaded successfully"
          content:
            application/json:
              schema:
                # EDIT REF
                $ref: "#/components/schemas/Emotion"
        500:
          description: "An error occurred"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/api/image/{imageName}":
    delete:
      tags:
        - "image"
      description: "Deletes a single image file"
      operationId: "delete-image"
      responses:
        200:
          description: "Deleted successfully"
        501:
          description: "An error occurred"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: "Entity not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    parameters:
      - in: path
        name: "imageName"
        description: "The name of the image which you want to delete"
        required: true
        schema:
          type: "string"
  "/api/face/{imageName}":
    get:
      tags:
        - "face"
      operationId: "post-face"
      responses:
        200:
          description: "Request successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Analysis"
        500:
          description: "An error occurred"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: "Entity not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    parameters:
      - in: path
        name: "imageName"
        description: "The name of the image which you an analysis of"
        required: true
        schema:
          type: "string"
      - in: body
        name: "userId"
        description: "Id of user"
        required: true
        schema:
          type: "number"
  "/api/statistic/{id}":
    get:
      tags:
        - statistic
      operationId: "get-statistic"
      responses:
        200:
          description: "Generated successfully some statistics"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Statistic"
        500:
          description: "An error occurred"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: "User not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      parameters:
        - in: path
          name: "id"
          description: "The user id."
          required: true
          schema:
            type: number
  "/login":
    post:
      tags:
        - login
      operationId: "login"
      responses:
        200:
          description: "Login successful."
          content:
            application/json:
              schema:
                $ref: "#component/schemas/User"
        422:
          description: "E-Mail or password invalid."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/register":
    post:
      tags:
        - register
      operationId: "register"
      responses:
        201:
          description: "Registration successful."
          content:
            application/json:
              schema:
                $ref: "#/schemas/User"
        401:
          description: "Username and/or password missing."
          content:
            application/json:
              schema:
                $ref: "#schema/Error"
        409:
          description: "E-Mail is already registered."
          content:
            application/json:
              schema:
                $ref: "#/schemas/Error"
  "/verifyAccount":
    get:
      tags:
        - verifyAccount
      operationId: "account_verification"
      responses:
        200:
          description: "User E-Mail successfully verified."
          content:
            application/json:
              schema:
                $ref: "#/schemas/User"
        404:
          description: "Activation link invalid or expired"
          content:
            application/json:
              schema:
                $ref: "#/schemas/Error"
components:
  schemas:
    User:
      properties:
        id:
          type: "number"
          format: "integer"
        name:
          type: "string"
        e-mail:
          type: "string"
        password:
          type: "string"
        analysis-count:
          type: "integer"
    Analysis:
      properties:
        id:
          type: "number"
          format: "integer"
        userId:
          type: "number"
          format: "integer"
        date:
          type: "string"
          format: "date"
        emotions:
          $ref: "#/components/schemas/Emotion"
        smile:
          type: "number"
          format: "double"
        accessories:
          type: "array"
          items:
            $ref: "#/components/schemas/Accessory"
        makeup:
          $ref: "#/components/schemas/MakeUp"
        glasses:
          type: "string"
        gender:
          type: "string"
        age:
          type: "integer"
        facialHair:
          $ref: "#/components/schemas/FacialHair"
        hair:
          $ref: "#/components/schemas/Hair"
    Emotion:
      properties:
        id:
          type: "number"
          format: "integer"
        anger:
          type: "number"
          format: "double"
        contempt:
          type: "number"
          format: "double"
        disgust:
          type: "number"
          format: "double"
        fear:
          type: "number"
          format: "double"
        happiness:
          type: "number"
          format: "double"
        neutral:
          type: "number"
          format: "double"
        sadness:
          type: "number"
          format: "double"
        surprise:
          type: "number"
          format: "double"
    Statistic:
      type: object
      properties:
        id:
          type: "number"
          format: "integer"
    Accessory:
      properties:
        id:
          type: "number"
          format: "integer"
        type:
          type: "string"
        confidence:
          type: "number"
          format: "double"
    MakeUp:
      properties:
        id:
          type: "number"
          format: "integer"
        eyeMakeup:
          type: "boolean"
        lipMakeup:
          type: "boolean"
    FacialHair:
      properties:
        id:
          type: "number"
          format: "integer"
        moustache:
          type: "number"
          format: "double"
        beard:
          type: "number"
          format: "double"
        sideburns:
          type: "number"
          format: "double"
    Hair:
      properties:
        bald:
          type: "number"
          format: "double"
        invisible:
          type: "boolean"
        hairColor:
          type: "array"
          items:
            $ref: "#/components/schemas/HairColor"
    HairColor:
      properties:
        color:
          type: "string"
        confidence:
          type: "number"
          format: "double"
    Error:
      properties:
        message:
          type: "string"
